# Generated by Django 4.2.19 on 2025-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_patient_allergies_alter_patient_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
