# Generated by Django 4.2.11 on 2025-03-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='questions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
