# Generated by Django 4.2.11 on 2025-03-12 19:35

from django.db import migrations, models
from datetime import date,time

class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_booking_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='questions',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastName',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(default=date.today, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
