# Generated by Django 4.2.11 on 2025-03-12 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
