# Generated by Django 4.2.11 on 2025-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_booking_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
