# Generated by Django 4.2.11 on 2025-03-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_booking_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
