# Generated by Django 4.2.11 on 2025-03-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_booking_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
    ]
