# Generated by Django 4.2.11 on 2025-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_booking_age_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
