# Generated by Django 4.2.11 on 2025-03-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_booking_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
    ]
