# Generated by Django 4.2.11 on 2025-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
