# Generated by Django 4.2.11 on 2025-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctors_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
