# Generated by Django 4.2.11 on 2025-03-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='name',
        ),
        migrations.AddField(
            model_name='doctors',
            name='available_days',
            field=models.CharField(default='', help_text='E.g., Monday, Wednesday, Friday', max_length=100),
        ),
        migrations.AddField(
            model_name='doctors',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
