# Generated by Django 4.2.11 on 2025-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctors_name_doctors_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
