# Generated by Django 4.2.11 on 2025-04-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctors_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='available_days',
            field=models.CharField(help_text='E.g., Monday, Wednesday, Friday', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
