# Generated by Django 4.2.11 on 2025-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctors_available_days_alter_doctors_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='available_days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
